on: push
jobs:
  update_db:
    name: "Database Updater"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.x'
    - name: "Fetch data"
      run: |
        python -m pip install tqdm requests
        cd parser && python parser.py && cd ../
    - name: "Tar files"
      run: tar -cvf eQitab_data.tar **/*.txt **/**/*.psv
    - name: "Upload tar file"
      uses: actions/upload-artifact@v3
      with:
        name: eQitab-data
        path: eQitab_data.tar
    - name: "Commit tar file"
      run: |
        rm eQitab_data.tar
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Push tar files" -a
    - name: "Push tar file"
      uses: ad-m/github-push-action@master
